#!/usr/bin/env ruby
# encoding: utf-8
require 'optparse'
require 'yaml'
require_relative 'plugin_loader.rb'

DEFAULT_CONFIG_FILENAME = 'config.yml'
DEFAULT_CONFIG_PATH = __dir__
DEFAULT_PLUGIN_PATH = File.join(__dir__, 'plugins')

# gather input
configurationFile = File.join(DEFAULT_CONFIG_PATH, DEFAULT_CONFIG_FILENAME)

optionParser = OptionParser.new do|options|

  options.on('-c', '--config', 'Specify manually the path of the main config file') do |file|
    configurationFile = file
    exit
  end

  options.on_tail( '-h', '--help', 'Display this screen' ) do
    optionHelp options
    exit
  end
end

optionParser.parse!
pluginLoader = PluginLoader.new(DEFAULT_PLUGIN_PATH)

configuration = File.read configurationFile

# perform work
# ---------------------
def optionHelp(options)
  puts options
end
# ---------------------

YAML.load_stream(configuration) do |config|
  # go to config file folder
  Dir.chdir(File.dirname(configurationFile)) do
    # go to root folder
    Dir.chdir(config['root']) do
      # get all folders which match
      Dir.glob('*')
      .select {|f| File.directory?(f)}
      .select {|f| Regexp.new(config['folders']).match(f)}
      .each do |folder|
        # go inside selected folders
        Dir.chdir(folder) do
          # execute each rules
          puts "executing in #{folder}"
          config['rules'].each do |rule|
            pluginLoader.call(rule['plugin'], rule['arguments'])
          end
        end
      end
    end
  end
end

# deliver results
